TrelloWorld/Models/TokenObject.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TrelloWorld.Models
{
    public class TokenObject
    {
        public string ID { get; set; }
        public string Value { get; set; }
    }

    public class TokenObjectDBContext : DbContext
    {
        public DbSet<TokenObject> TokenObjects { get; set; }
    }
}

TrelloWorld/Controllers/AuthController.cs
using System;
using System.Web.Mvc;
using TrelloWorld.Services;

namespace TrelloWorld.Controllers
{
    public class AuthController : Controller
    {
        private IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        // GET: Auth
        public ActionResult Index()
        {
            if (!_authService.IsUserAuthenticated()) 
            {
                var authRouteUrl = _authService.GenerateAuthRouthUrl();

                return Redirect(authRouteUrl);
            }
            
            return RedirectToUserBoards();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult FetchToken(string tokenValue)
        {
            try
            {
                if (_authService.AuthenticateUser(tokenValue))
                    return RedirectToUserBoards();
            }
            catch (Exception)
            {
                _authService.LogoutUser();
                return View("AppError");
            }

            return RedirectHome(); //user denied access
        }

        public ActionResult Logout()
        {
            _authService.LogoutUser();

            return RedirectHome();
        }

        private ActionResult RedirectToUserBoards()
        {
            return RedirectToAction("Index", "Boards");
        }

        private ActionResult RedirectHome()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

TrelloWorld/Controllers/BoardsController.cs
using System;
using System.Web.Mvc;
using TrelloWorld.Services;

namespace TrelloWorld.Controllers
{
    public class BoardsController : Controller
    {
        private ITrelloService _trelloService;

        public BoardsController(ITrelloService trelloService)
        {
            _trelloService = trelloService;
        }

        // GET: Boards
        public ActionResult Index()
        {
            try
            {
                var userBoards = _trelloService.GetMemberBoards();
                return View(userBoards);
            }
            catch (UnauthorizedAccessException)
            {
                return RedirectToAuthErrorPage();
            }
            catch (NullReferenceException)
            {
                return RedirectToAuthErrorPage();
            }
            catch (ArgumentException)
            {
                return RedirectToAppErrorPage();
            }
        }

        public ActionResult Cards(string boardId) 
        {
            try
            {
                var cards = _trelloService.GetCards(boardId);
                ViewBag.BoardName = _trelloService.GetBoardName(boardId);

                return View(cards);
            }
            catch (NullReferenceException)
            {
                return RedirectToAuthErrorPage();
            }
            catch (UnauthorizedAccessException)
            {
                return RedirectToAuthErrorPage();
            }
        }

        public ActionResult AddComment(string cardId)
        {
            try
            {
                var card = _trelloService.GetCard(cardId);

                ViewBag.CardName = card.Name;

                return View(card);
            }
            catch (NullReferenceException)
            {
                return RedirectToAuthErrorPage();
            }
            catch (UnauthorizedAccessException)
            {
                return RedirectToAuthErrorPage();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment(string cardId, string newComment)
        {
            try
            {
                var card = _trelloService.UpdateComment(cardId, newComment);

                return RedirectToAction("Cards", "Boards", new { boardId = card.Board.Id });
            }
            catch (NullReferenceException)
            {
                return RedirectToAuthErrorPage();
            }
            catch (UnauthorizedAccessException)
            {
                return RedirectToAuthErrorPage();
            }
        }

        private ActionResult RedirectToAuthErrorPage()
        {
            return View("AuthError");
        }

        private ActionResult RedirectToAppErrorPage()
        {
            return View("AppError");
        }
    }
}

TrelloWorld/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TrelloWorld.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

TrelloWorld/Views/Boards/AddComment.cshtml
@model Manatee.Trello.Card
@{
    ViewBag.Title = "Add Comment";
}

<h2>@ViewBag.CardName - Add Comment</h2>

<form action="/Boards/AddComment/@Model.Id" , method="post">
    @Html.AntiForgeryToken()
    @Html.Hidden("cardId", Model.Id, new { @id = "cardId"})
    <input type="text" name="newcomment" />
    <input type="submit" value="Submit">
</form>

<div>
    @Html.ActionLink("Cancel", "Cards", new { boardId = Model.Board.Id })
</div>

TrelloWorld/Views/Boards/Cards.cshtml
@model IEnumerable<Manatee.Trello.Card>
@{
    ViewBag.Title = "Cards";
}

<h2>@ViewBag.BoardName - Cards</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
        </th>
    </tr>

    @foreach (var card in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => card.Name)
            </td>
            <td>
                @Html.ActionLink("Add Comment", "AddComment", new { cardId = card.Id })
            </td>
        </tr>
    }

</table>

@Html.ActionLink("Back to boards", "Index", "Board", new {})

TrelloWorld/Views/Boards/Index.cshtml
@model IEnumerable<Manatee.Trello.Board>

@{
    ViewBag.Title = "Boards";
}

<h2>Boards</h2>

@if(Model.Count() == 0){
    <h3>No boards to show.</h3>
} else {
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
            </th>
        </tr>

        @foreach (var board in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => board.Name)
                </td>
                <td>
                    @Html.ActionLink("Cards", "Cards", new { boardId = board.Id })
                </td>
            </tr>
        }

    </table>
}

TrelloWorld/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome";
}

<div class="jumbotron">
    <h1>TrelloWorld</h1>
    <p class="lead">This app lets you view your boards and cards on Trello, and even add comments to your cards!</p>
    @Html.ActionLink("View my boards from Trello", "Index", "Auth")
</div>


TrelloWorld/Views/Shared/AppError.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Application Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>
<h2 class="text-danger">Please try again later.</h2>


TrelloWorld/Views/Shared/AuthError.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Authentication Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>
<h2 class="text-danger">Please <a href="/Auth">reauthenticate</a> and try again.</h2>


TrelloWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TrelloWorld</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TrelloWorld", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @if(HttpContext.Current.Request.Cookies[TrelloWorld.Common.TrelloWorldConfiguration.CookieKey] != null ){
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Logout", "Logout", "Auth")</li>
                    </ul>
                </div>
            }
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TrelloWorld</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>